# Generated by Django 4.0.4 on 2022-05-25 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=50)),
                ('gpa', models.CharField(max_length=3)),
                ('mob', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('activation', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='webadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_fname', models.CharField(max_length=50)),
                ('admin_lname', models.CharField(max_length=50)),
                ('admin_email', models.CharField(max_length=50)),
                ('admin_password', models.CharField(max_length=50)),
            ],
        ),
    ]
